/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllRecords' : IDL.Func([], [], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllNotesSortedByTimestamp' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllSessionRecords' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyTimeLimit' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getNoteById' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
  'getTodaysSessionRecords' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSessionRecord' : IDL.Func([IDL.Int, IDL.Int], [], []),
  'setDailyTimeLimit' : IDL.Func([IDL.Nat], [], []),
  'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllRecords' : IDL.Func([], [], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllNotesSortedByTimestamp' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllSessionRecords' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyTimeLimit' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getNoteById' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'getTodaysSessionRecords' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSessionRecord' : IDL.Func([IDL.Int, IDL.Int], [], []),
    'setDailyTimeLimit' : IDL.Func([IDL.Nat], [], []),
    'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };